version: '1.0.0'
services:
  nginx:
    build:
      context: .
      dockerfile: ./infra/dev/nginx/nginx.Dockerfile
    ports: 
      - "80:80"
    volumes:
      - ./infra/dev/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./infra/dev/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www/html
  php:
    build:
      context: .
      dockerfile: ./infra/dev/php/php.Dockerfile
    volumes:
      - ./infra/dev/php/conf.d/php.ini:/usr/local/etc/php/conf.d/99-custom.ini
      - ./:/var/www/html
    depends_on:
      - db
      - redis
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  mailpit:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
