version: '1.0.0'
services:
  nginx:
    build:
      context: .
      dockerfile: ./infra/dev/nginx/nginx.Dockerfile
    ports: 
      - "80:80"
    volumes:
      - ./infra/dev/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
  php:
    build:
      context: .
      dockerfile: ./infra/dev/php/php.Dockerfile
    volumes:
      - ./:/var/www/html
